# Generated by Django 3.0.5 on 2023-05-05 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='age',
        ),
        migrations.RemoveField(
            model_name='followers',
            name='gender',
        ),
    ]
